syntax = "proto3";

package debugger;

message AcquireBusRequest {
}
message ReleaseBusRequest {
}

enum ErrType {
    ERROR_TYPE_UNSPECIFIED = 0;
    ERROR_TYPE_OK = 1;
    ERROR_TYPE_TIMEOUT = 2;
    ERROR_TYPE_FATAL = 3;
}

message ErrorResponse {
    ErrType err_type = 1;
    optional string msg = 2;
}

message RpcRequest {
    uint32 request_id = 1;

    oneof payload {
        AcquireBusRequest acquire_bus = 2;
        ReleaseBusRequest release_bus = 3;
    }
}

message RpcResponse {
    uint32 request_id = 1;

    oneof payload {
        ErrorResponse acquire_bus = 2;
        ErrorResponse release_bus = 3;
    }
}
